### ISSUE TITLE
No module named whatsappCli.__main__

### ISSUE THREAD

**Issue by mursitaffandi** [yausername/whatsapp-cli#2]
i use sudo because , whene i not use sudo error apear
[
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/websocket'
Consider using the `--user` option or check the permissions.
]
sudo pip install --user whatsapp-cli
[
When I installing this lib , show warning
The directory '/home/$USER/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/$USER/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Installing collected packages: websocket-client, click, certifi, chardet, idna, urllib3, requests, whatsapp-cli
  The script chardetect is installed in '/home/$USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script whatsapp-cli is installed in '/home/$USER/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2018.4.16 chardet-3.0.4 click-6.7 idna-2.6 requests-2.18.4 urllib3-1.22 websocket-client-0.48.0 whatsapp-cli-0.1.1
]

whene i run command = whatsapp-cli
[
Traceback (most recent call last):
  File "/home/$USER/.local/bin/whatsapp-cli", line 7, in <module>
    from whatsappCli.__main__ import main
ImportError: No module named whatsappCli.__main__
]

**Comment by mursitaffandi** [comment]
running on ubuntu 16.04 LTS 
python version 2.7
pip version pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
Shell Zsh

**Comment by yausername** [comment]
Sorry for late reply :D
you can try this command
`sudo pip install whatsapp-cli`
