### ISSUE TITLE
can't message user or list

### ISSUE THREAD

**Issue by CanerEren** [yausername/whatsapp-cli#7]
I have set up pushbullet, got it working. Recieved message and got notified. but i cant see the contact in cli or list any contacts ?

**Comment by yausername** [comment]
whatsapp-cli must be running in interactive mode while you are receiving
the message.
Alternatively you can add contact manually using

Usage: whatsapp-cli add [OPTIONS]

  Add a contact

Options:
  -u TEXT  Name of the person/group as it appears in your contacts  [required]
  -m TEXT  12 digit mobile number  [required]

**Comment by CanerEren** [comment]
Thanks, I have added contact now. but i can't send anything.

`Exception in thread Thread-10:                                                                                                                                                                                   │
└──────────────────────────────Traceback (most recent call last):─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
                                                                   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                                                                                                                                                                 self.run()
                                                                                                                                                                                                             File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
                                                                                                          self.__target(*self.__args, **self.__kwargs)
                                                                                                                                                        File "/Library/Python/2.7/site-packages/whatsappCli/ui/curses_ui.py", line 70, in execute
                                  self.__send_message(command.strip(), win_index)
                                                                                   File "/Library/Python/2.7/site-packages/whatsappCli/ui/curses_ui.py", line 134, in __send_message
                                                                                                                                                                                        self.feeder.post(contacts[self.windows[win_index].usr_tag], command)
                                           File "/Library/Python/2.7/site-packages/whatsappCli/feed/pb_feeder.py", line 53, in post
                                                                                                                                       req["push"]["source_user_iden"] = config["source_user_iden"]
                                                                                                                                                                                                   KeyError: 'source_user_iden'
`

**Comment by yausername** [comment]
Are you able to see received messages in ui mode?

**Comment by CanerEren** [comment]
what is ui mode?

**Comment by yausername** [comment]
The normal Interactive (Curses) Mode shown in the readme

**Comment by yausername** [comment]
See this from the readme -
To be able to send messages you need to receive at least one message after
starting the application for seeding the conf (default location
~/.whatsapp-cli/conf).

**Comment by CanerEren** [comment]
how can i seed conf, i can't receive messages. i'm in the dir right now

**Comment by CanerEren** [comment]
`source_user_iden,ujxDbWTFXBA
source_device_iden,ujxDbWTFXBAsjCy2EANtVQ `

this is inside the conf file

**Comment by yausername** [comment]
Looks ok. Can you try to send again?

**Comment by CanerEren** [comment]
oh it works now 👍

**Comment by CanerEren** [comment]
one more thing,
i can't erase anything in cli, like backspace does not work at all. is this normal?

**Comment by yausername** [comment]
> one more thing,
> i can't erase anything in cli, like backspace does not work at all. is this normal?


It works for me on ubuntu. What OS are you on? Might be a bug.

**Comment by CanerEren** [comment]
macOS 10.13.6

**Comment by yausername** [comment]
> macOS 10.13.6

hmm, I never tested on macOS. This is definitely a bug then.

**Comment by CanerEren** [comment]
are you gonna look into it?

**Comment by yausername** [comment]
I am busy with other things right now. So maybe some time in future.

**Comment by CanerEren** [comment]
okay dude, have a nice week. thanks for the help :)
