### ISSUE TITLE
CPU usage too high.

### ISSUE THREAD

**Issue by kimpla7** [yausername/whatsapp-cli#8]
As the title says, whatsapp-cli makes use of almost 25% of my CPU usage on average. I think that's way too much taking into consideration that I'm using an i5-8220. Is there a way to reduce this?

Thank you.

**Comment by yausername** [comment]
Hey, 
Thanks for reporting the issue. I have fixed it.
Install the newer version using this command.
`sudo pip install whatsapp-cli --upgrade`
Thanks

**Comment by kimpla7** [comment]
Hello,

Now that problem is solved, but I cannot send any messages using the /chat
command, whilst I could do it yesterday. Is there anything you can do?

**Comment by yausername** [comment]
Hi,
This thing is very limited in what it can do
* You cannot initiate chat with users from whom you have not received a notification in the recent past. This is a pushbullet limitation as it uses reply to notification to send messages.

So `/chat` should work after the person sends you a text and you get the notification.
Hope it helps.
Thanks

**Comment by kimpla7** [comment]
I know how it works, I really liked it back yesterday when I tried it for the first time. I'm trying to chat with a person who has just sent me a notification seconds before, but it's not working as before the update.

**Comment by yausername** [comment]
are you able to receive messages?
does the person show up when you call the `/users` command

**Comment by kimpla7** [comment]
Yes, I am able to receive messages and also the person appears in the /users command. I can also access to the chat window but when I type and press enter, nothing happens.

**Comment by yausername** [comment]
that's strange.
maybe wait a couple of seconds after opening and try to send message then.
or close and open again.

**Comment by kimpla7** [comment]
I tried that already and it isn't working. I also tried to generate a new token but cannot send messages. It could be something related with the update, because it was working just fine before.

**Comment by yausername** [comment]
try this command
`whatsapp-cli --token yourtoken send -u "Name" -m "message"`

**Comment by kimpla7** [comment]
Nothing :/

**Comment by yausername** [comment]
what error does it print?

**Comment by yausername** [comment]
> try this command
> `whatsapp-cli --token yourtoken send -u "Name" -m "message"`

this is a separate command

**Comment by kimpla7** [comment]
What do you mean separate?

**Comment by yausername** [comment]
> What do you mean separate?

not to be used in the visual mode but on the command line. if that was not obvious

**Comment by yausername** [comment]
> I tried that already and it isn't working. I also tried to generate a new token but cannot send messages. It could be something related with the update, because it was working just fine before.

It should work with the newer token then. I don't think it is related to the update because it works for me. you can downgrade and check though.

**Comment by kimpla7** [comment]
Ok, as you say. It's sad it won't work for me.

**Comment by kimpla7** [comment]
Can it be something related with Pushbullet? It says that I've reached the free messages for this month.
Okay, now I see it's because of this: 

Send messages (SMS, WhatsApp, Kik, etc) | 100/month
-- | --

Thanks for your time.

**Comment by yausername** [comment]
Ok. I'm glad you found out the issue.
Cheers!
